### ISSUE TITLE
What if there exist few common songs between these 2 apps

### ISSUE THREAD

**Issue by Manan2k4** [angstyfrostyneko/spotify-to-vimusic#3]

**Comment by angstyfrostyneko** [comment]
I don't understand your question, can you explain it further and give an example?

**Comment by Manan2k4** [comment]
Please forget about that portion. I got another doubt, that if I try to add songs from "songlist.txt" to my "Favourites" playlist in vimusic, then will my entire playlist in vimusic will be overwritten?
________________________________

**Comment by angstyfrostyneko** [comment]
It shouldn't be overwritten, I have made it so that it appends to the current favorites instead of overwriting them, so it will keep both existing songs and add the new ones.
And as for your previous question, I think I understood what you mean. If a song is found to already exist in the database, as long as the song IDs match, it will be skipped and not added again, leaving the original untouched.

I highly recommend keeping a copy of the database around before it's edited by this script anyway, just in case that something gets messed up.

**Comment by Manan2k4** [comment]
Thanks for the tip!
